CREATE TABLE IF NOT EXISTS raw_weather_data(
   RAW_JSON VARCHAR,
   TIMESTAMP TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS weather_data(
    LATITUDE DECIMAL,
    LONGITUDE DECIMAL,
    TEMPERATURE DECIMAL,
    RELATIVE_HUMIDITY DECIMAL, 
    WIND_SPEED DECIMAL, 
    CLOUD_COVER DECIMAL,
    TIMESTAMP TIMESTAMP WITH TIME ZONE
);
CREATE TABLE IF NOT EXISTS weather_data_view(
    LATITUDE DECIMAL,
    LONGITUDE DECIMAL,
    DATE DATE,
    HOUR INT,
    AVG_TEMPERATURE DECIMAL,
    AVG_HUMIDITY DECIMAL,
    AVG_WIND_SPEED DECIMAL,
    AVG_CLOUD_COVER DECIMAL,
    mm_temp DECIMAL
);